spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: postgres
    password: sua_senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    port: 8080
